dataset:
  num_channels: 1
  mean: [ 0. ]
  std: [ 1. ]
  img_width: 32
  img_height: 32
  train_dataset_params:
    num_images: 10000
  valid_dataset_params:
    num_images: 1000
  test_dataset_params:
    num_images: 1000

run:
  n_epochs: 200
  current_epoch: 0
  batch_size: 512
  num_workers: 0
  store_state_path: "../tmp/autoencoder/checkpoints/baseline.ckpt"
  load_state_path: None

logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "net-fragments-ae-baseline"
    log_model: True
    group: base
    job_type: train
  console:
    active: True

optimizer:
  lr: 0.0001
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 0.00000001

feature_extractor:
  out_channels: 4
  s1_params:
    use_larger_weights: False
    threshold_f: 'threshold'