dataset:
  num_channels: 1
  mean: [ 0. ]
  std: [ 1. ]
  img_width: 32
  img_height: 32
  train_dataset_params:
    num_images: 300
  valid_dataset_params:
    num_images: 4
  test_dataset_params:
    num_images: 60

run:
  n_epochs: 101
  current_epoch: 0
  batch_size: 1
  num_workers: 0
  plots:
    enable: True
    only_last_epoch: False
    store_path: "../tmp/test/"
  store_state_path: None
  load_state_path: None

logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "net-fragments-final"
    log_model: True
    group: base
    job_type: train
  console:
    active: True

n_alternative_cells: 10

feature_extractor:
  out_channels: 4
  s1_params:
    use_larger_weights: False
    threshold_f: 'threshold'

lateral_model:
  channels: 4
  max_timesteps: 6
  s2_params:
    locality_size: 5
    lr: 0.2
    neg_corr: True
    act_threshold: 0.5
    square_factor:
      - 1.2
      - 1.4
      - 1.6
      - 1.8
      - 2.0
      - 2.2
    support_factor: 1.3