dataset:
  num_channels: 1
  mean: [ 0. ]
  std: [ 1. ]
  img_width: 32
  img_height: 32
  train_dataset_params:
    num_images: 300
  valid_dataset_params:
    num_images: 4
  test_dataset_params:
    num_images: 60

run:
  n_epochs: 50
  current_epoch: 0
  plots:
    enable: True
    only_last_epoch: False
    store_path: "../tmp/test/"
  store_state_path: None
  load_state_path: None

logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "net-fragments"
    log_model: True
    group: null
    job_type: null
  console:
    active: True

n_alternative_cells: 10

feature_extractor:
  out_channels: 4
  bin_threshold: 0.  # set to 0.5 to obtain better features

lateral_model:
  channels: 4
  max_timesteps: 2  # 1 = only one forward pass without recurrent connection
  s2_params:
    locality_size: 5
    lr: 0.2
    neg_corr: True
    act_threshold: 0.5  # 'bernoulli'
    square_factor:
      - 1.2
      - 1.4
      - 1.6
      - 1.8
      - 2.0
      - 2.2
    support_factor: 1.3